
def getAdjetivos():
  # Base de adjetivos para classificar a qualidade dos comentários (atualizada)

  return {
    # Adjetivos Bons (pontuações positivas)
    "ótimo": 3,
    "excelente": 3,
    "maravilhoso": 3,
    "confiável": 2,
    "durável": 2,
    "prático": 2,
    "eficiente": 2,
    "útil": 2,
    "agradável": 2,
    "incrível": 3,
    "perfeito": 3,
    "funcional": 2,
    "rápido": 2,
    "confortável": 2,
    "bonito": 1,
    "econômico": 1,
    "versátil": 2,
    "inovador": 3,
    "robusto": 2,
    "bem-acabado": 2,
    "moderno": 2,
    "fantástico": 3,
    "impressionante": 3,
    "refinado": 2,
    "seguro": 2,
    "razoável": 1,
    "potente": 2,
    "preciso": 2,
    "suave": 2,
    "elegante": 2,
    "compacto": 2,
    "satisfatório": 1,
    "harmonioso": 2,
    "estável": 2,
    "resistente": 2,
    "inteligente": 3,
    "valioso": 3,
    "atrativo": 2,
    "qualificado": 2,
    "bom": 2,

    # Adjetivos Ruins (pontuações negativas)
    "horrível": -3,
    "frágil": -2,
    "inútil": -3,
    "decepcionante": -3,
    "caro": -1,
    "lento": -2,
    "desconfortável": -2,
    "fraco": -2,
    "defeituoso": -3,
    "complicado": -2,
    "malfeito": -3,
    "ineficiente": -3,
    "péssimo": -3,
    "desgastado": -2,
    "arcaico": -2,
    "incômodo": -2,
    "barulhento": -1,
    "limitado": -1,
    "desatualizado": -2,
    "irritante": -2,
    "inferior": -2,
    "instável": -3,
    "frustrante": -3,
    "medíocre": -3,
    "estragado": -3,
    "enganador": -3,
    "problemático": -3,
    "exagerado": -1,
    "inseguro": -2,
    "lamentável": -3,
    "irracional": -2,
    "desajeitado": -2,
    "improdutivo": -3,
    "sem graça": -1,
    "limitante": -2,
    "precário": -3,
    "estridente": -1,
    "desagradável": -2,
    "sem valor": -3
}